# -*- coding: utf-8 -*-
"""Leaving_Certificate.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1m5eQ0SwUq6zt5rc2gWRgKf8qalronUz1
"""

#!pip install easyocr
#!pip install opencv-python-headless==4.1.2.30
import cv2
import numpy as np
import re
import easyocr


class LC_OCR():

  def __init__(self,img_path):
    self.img_path = img_path
    self.reader = easyocr.Reader(['en'])
    print("Object created")


  def clean_text(self,text):
    sname = None
    text1 = []
    lines = text.split(',')
    for lin in lines:
      s = lin.strip()
      s = lin.replace('\n','')
      s = s.rstrip()
      s = s.lstrip()
      text1.append(s)
    lineno = 0
    print("length of string:",len(text1))
    for wordline in text1:
      xx = wordline.split(' ')
      if ([w for w in xx if re.search('(SCHOOL|SCH00L|GURUKUL|VIDHYALAYA|NIKETAN|VIDHYA|VIHAR|BHAVAN|MANDIR|PATHSHALA|SHALA)$', w.upper())]):
        if ([w for w in xx if re.search('(ID|LEAVING|CERTI|CERTIFICATE)$', w.upper())]):
          continue
        else:
          text1 = list(text1)
          lineno = text1.index(wordline)
          break

    sname = text1[lineno]
    print("Detected Name",sname)
    try:
  # Cleaning first names
        sname = sname.rstrip()
        sname = sname.lstrip()
        sname = sname.replace("8", "B")
        sname = sname.replace("0", "D")
        sname = sname.replace("6", "G")
        sname = sname.replace("1", "I")


    except:
            pass

    return sname

  def get_detail(self):
    detection_result = self.reader.detect(self.img_path,
                              width_ths=0.7, 
                              mag_ratio=1.5
                              )
    text_coordinates = detection_result[0][0]
    recognition_results = self.reader.recognize(self.img_path,
                                 horizontal_list=text_coordinates,
                                 free_list=[]
                                 )
    detected_text = [txt[1] for txt in recognition_results]
    detected_text = ",".join(detected_text)
    print("Detected Text:",detected_text)
    return self.clean_text(detected_text)

